import { test, expect } from '@playwright/test';

test('templates come first, camera is filters only, editor customizations export and persist',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/#gallery');await expect(page.locator('.template-card-choice')).toHaveCount(12);await expect(page.locator('.template-card-choice img')).toHaveCount(12);await page.screenshot({path:'test-results/template-library.png',fullPage:true});await expect(page.getByText('ARCHIVE',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'SOLO MODE',exact:true}).click();await page.locator('.template-card-choice').filter({hasText:'Minimal'}).click();
 await expect(page.getByText('READY',{exact:true})).toBeVisible();await expect(page.locator('.side-template-item,.frame-picker')).toHaveCount(0);await expect(page.locator('.side-filter-item')).toHaveCount(32);
 for(const filter of await page.locator('.side-filter-item').all()){await filter.click();await expect(filter).toHaveClass(/selected/);}
 await page.getByRole('button',{name:'Original',exact:true}).click();await page.getByRole('button',{name:'3',exact:true}).click();await page.getByRole('button',{name:'Start capture',exact:true}).click();
 for(let i=0;i<3;i++){await page.getByRole('button',{name:'Take photo',exact:true}).click();await expect(page.locator('.shot-boxes img')).toHaveCount(i+1);}
 await page.getByRole('button',{name:'DONE — SELECT PHOTOS'}).click();await expect(page.locator('.select-card')).toHaveCount(3);for(const photo of await page.locator('.select-card').all())await photo.click();await page.getByRole('button',{name:'CONTINUE TO CUSTOMIZE'}).click();
 await expect(page.locator('.frame-picker')).toBeVisible();await expect(page.getByRole('button',{name:'TEMPLATE',exact:true})).toHaveCount(0);await expect(page.locator('.side-filter-item')).toHaveCount(0);
 await page.getByRole('tab',{name:/^Studio /}).click();await expect(page.locator('.frame-option')).toHaveCount(12);await page.locator('.frame-option').first().click();
 await page.getByRole('button',{name:'BACKGROUND',exact:true}).click();await page.getByLabel('Custom background color').fill('#bbccdd');await page.getByRole('button',{name:'Linen',exact:true}).click();await page.getByLabel('Texture strength').fill('0.8');
 await page.getByRole('button',{name:'BORDER',exact:true}).click();await page.getByRole('button',{name:'SCALLOP',exact:true}).click();await page.getByLabel('Custom border color').fill('#ab3456');await page.getByLabel('Border width').fill('9');
 await page.getByRole('button',{name:'TEXT',exact:true}).click();await page.getByRole('checkbox',{name:'ADD TEXT TO MY STRIP'}).check();await page.getByLabel('TITLE',{exact:false}).fill('Our memories');await page.getByLabel('Caption font').selectOption('Pacifico');await page.getByLabel('Text horizontal position').fill('0.3');await page.getByLabel('Text vertical position').fill('0.15');await page.getByLabel('Text size').fill('1.8');
 await page.getByRole('button',{name:'PLACE TEXT ON PREVIEW'}).click();await page.getByAltText('Your photo strip').click({position:{x:90,y:70}});
 await page.getByRole('button',{name:'STICKERS',exact:true}).click();await page.getByLabel('Custom symbol').fill('♡');await page.getByRole('button',{name:'ADD SYMBOL',exact:true}).click();await page.getByLabel('Sticker size',{exact:true}).fill('2');await page.getByLabel('Sticker x',{exact:true}).fill('0.7');await page.getByLabel('Sticker y',{exact:true}).fill('0.2');await page.locator('.sticker-btn').first().click();await page.getByRole('button',{name:'REMOVE SELECTED STICKER'}).click();await expect(page.getByLabel('Selected sticker').locator('option')).toHaveCount(1);
 await page.screenshot({path:'test-results/design-editor.png',fullPage:true});await page.getByRole('button',{name:'NEXT STEP'}).click();await expect(page.getByAltText('Finished photo strip')).toHaveAttribute('src',/^data:image/);const source=await page.getByAltText('Finished photo strip').getAttribute('src');await page.reload();await expect(page.getByAltText('Finished photo strip')).toHaveAttribute('src',source!);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'DOWNLOAD STRIP',exact:true}).click();expect((await download).suggestedFilename()).toBe('flashback-strip.jpg');await page.getByRole('button',{name:'CONTINUE CUSTOMIZING'}).click();for(const width of [360,768,1024,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await expect(page.getByAltText('Your photo strip')).toBeVisible();}expect(errors).toEqual([]);
});

test('textures, custom colors, borders, text placement and sticker sizes change exported pixels',async({page})=>{
 test.skip(Boolean(process.env.APP_BASE_URL),'Source modules are only available locally.');await page.goto('/');
 const output=await page.evaluate(async()=>{const {generatePhotoStrip,DEFAULT_CUSTOMIZATION,STRIP_TEXTURES,STRIP_BORDERS}=await import('/src/utils/photoStrip.ts');const c=document.createElement('canvas');c.width=80;c.height=60;c.getContext('2d')!.fillRect(0,0,80,60);const photo=c.toDataURL();const create=(patch:object)=>generatePhotoStrip([photo],{...DEFAULT_CUSTOMIZATION,template:'EDITORIAL',layout:'single',...patch});const none=await create({});const textures=[];for(const texture of Object.keys(STRIP_TEXTURES).filter(key=>key!=='NONE'))textures.push(await create({texture,textureStrength:.8}));const borders=[];for(const border of ['SCALLOP','LACE','POSTAGE','CHECKER','CORNERS'])borders.push(await create({border}));const words={showText:true,titleText:'Our memories'};return {none,textures,borders,borderCount:Object.keys(STRIP_BORDERS).length,custom:await create({background:'#bbccdd',border:'CUSTOM',borderColor:'#ff0000',borderWidth:12}),textA:await create({...words,textX:.5,textY:.2}),textB:await create({...words,textX:.2,textY:.7}),stickerA:await create({stickers:[{emoji:'♡',x:.5,y:.2,size:1}]}),stickerB:await create({stickers:[{emoji:'♡',x:.5,y:.2,size:3}]})};});
 for(const src of [...output.textures,...output.borders,output.custom])expect(src).not.toBe(output.none);expect(new Set(output.textures).size).toBe(output.textures.length);expect(new Set(output.borders).size).toBe(5);expect(output.borderCount).toBe(25);expect(output.textA).not.toBe(output.textB);expect(output.stickerA).not.toBe(output.stickerB);
});

for(const width of [360,768,1024,1280,1440,1920])test(`new workflow remains accessible at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});for(const view of ['home','gallery','preview','couple-create','makers']){await page.goto(`/#${view}`);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),view).toBe(true);if(view==='preview'){await expect(page.locator('.side-filter-item')).toHaveCount(32);await expect(page.locator('.frame-picker,.side-template-item')).toHaveCount(0);}}
});

 test('home entry points select the right mode before the visual template library',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'START TOGETHER',exact:true}).click();await expect(page.getByRole('button',{name:'LONG-DISTANCE MODE',exact:true})).toHaveAttribute('aria-pressed','true');await page.locator('.template-card-choice').filter({hasText:'Minimal'}).click();await expect(page.getByPlaceholder('Your name / your city')).toBeVisible();await page.goto('/');await page.getByRole('button',{name:'LAUNCH SESSION',exact:true}).click();await expect(page.getByRole('button',{name:'SOLO MODE',exact:true})).toHaveAttribute('aria-pressed','true');await page.locator('.template-card-choice').filter({hasText:'Classic'}).click();await expect(page.locator('.camera-preview')).toBeVisible();});
